### PR TITLE
Allow sanitizing arrays of all types while preserving primitive values

### PR DESCRIPTION
**Pull request by arhimondr**
The sanitizeByteCharArraysOnly allows to apply sanitation to byte[] and char[] arrays only. However in certain cases other type of arrays may also contain data needed to be sanitized. The new flag allows enabling sanitation for all arrays while keeping the primitive values (fields, stack values) untouched.

### CODE REVIEW

**Comment by arhimondr** [comment]
Thanks for creating this project. We have the very same problem with capturing heap dumps and we find this project extremely useful. 

In our use case it is important to avoid sanitation of primitive values as those are necessary for diagnostics.

In the future we would like to further improve it to allow sanitation of all but certain selected fields / stack frames that can be specified by an explicit allow list. Would you be interested in such contribution?

**Comment by maxxedev** [comment]
Should there be a test for this change?

Thanks, and yes, very interested in further contributions!

**Comment by arhimondr** [comment]
@maxxedev I was trying to find a test for the existing `sanitizeByteCharArraysOnly` flag to follow it by example, but couldn't find one. Could you please point me out to one (if one exist) or maybe provide a suggestion at what level would you prefer a test to be added?

**Comment by maxxedev** [comment]
Take a look at [HeapDumpSanitizerTest](https://github.com/paypal/heap-dump-tool/blob/heap-dump-tool-1.1.2/src/test/java/com/paypal/heapdumptool/sanitizer/HeapDumpSanitizerTest.java#L96-L118) and see if a new test is needed and if one can be added with reasonable effort.

I will be happy to merge the PR regardless.

**Comment by arhimondr** [comment]
@maxxedev Added additional tests, please take a look

**Comment by maxxedev** [comment]
Thanks. It's been released

**Pull request merged**
